# Generated by Django 3.2.12 on 2022-04-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0003_auto_20220402_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
    ]
