# Generated by Django 3.2.12 on 2022-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0005_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
