# Generated by Django 3.2.12 on 2022-04-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0006_requirement_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='descriptiion',
            new_name='description',
        ),
    ]
