# Generated by Django 3.2.12 on 2022-04-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0007_rename_descriptiion_requirement_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='postJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.company')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.requirement')),
            ],
        ),
    ]
