# Generated by Django 3.2.12 on 2022-04-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='Categorys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.category'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.company'),
        ),
    ]
