# Generated by Django 3.2.12 on 2022-04-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0012_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='address',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
    ]
