# Generated by Django 3.2.12 on 2022-04-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0014_auto_20220419_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question1', models.CharField(max_length=400, null=True)),
                ('answer1', models.CharField(max_length=400, null=True)),
                ('Question2', models.CharField(max_length=400, null=True)),
                ('answer2', models.CharField(max_length=400, null=True)),
                ('Question3', models.CharField(max_length=400, null=True)),
                ('answer3', models.CharField(max_length=400, null=True)),
                ('Question4', models.CharField(max_length=400, null=True)),
                ('answer4', models.CharField(max_length=400, null=True)),
                ('Question5', models.CharField(max_length=400, null=True)),
                ('answer5', models.CharField(max_length=400, null=True)),
                ('Question6', models.CharField(max_length=400, null=True)),
                ('answer6', models.CharField(max_length=400, null=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.application')),
            ],
        ),
    ]
