# Generated by Django 3.2.12 on 2022-04-19 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0015_aptitude_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitude_questions',
            name='USER',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.user'),
        ),
    ]
