# Generated by Django 3.2.12 on 2022-04-19 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0017_aptitude_questions_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.user'),
        ),
    ]
