# Generated by Django 3.2.12 on 2022-04-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0019_group_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_discussion',
            name='link',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
