# Generated by Django 3.2.12 on 2022-04-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0020_group_discussion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status1',
            field=models.CharField(default='not approved', max_length=100, null=True),
        ),
    ]
