# Generated by Django 3.2.12 on 2022-04-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0021_application_status1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_discussion',
            name='link',
            field=models.URLField(default='test', max_length=400, null=True),
        ),
    ]
