# Generated by Django 3.2.12 on 2022-04-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0022_alter_group_discussion_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_discussion',
            name='status1',
            field=models.CharField(default='test', max_length=400),
        ),
    ]
