# Generated by Django 3.2.12 on 2022-04-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0023_group_discussion_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_discussion',
            name='status1',
        ),
    ]
