# Generated by Django 3.2.12 on 2022-04-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0027_auto_20220421_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_discussion',
            name='date',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='one_to_one',
            name='date',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
