# Generated by Django 3.2.12 on 2022-04-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RECRUITMENT_APP', '0028_auto_20220421_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='offerletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.ImageField(null=True, upload_to='images/')),
                ('status', models.CharField(default='test', max_length=400)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.user')),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RECRUITMENT_APP.application')),
            ],
        ),
    ]
